### PR TITLE
feat: update bindings.ts file when string release is passed

### LINKED ISSUE #73: feat: Have release builds always generate a new bindings.ts file
As the title states, it would be nice if on a release the bindings.ts file was updated, especially in the case where a value was passed as the `--release` argument. Otherwise the committed version is going to be used, and if you are pointing to a github release or something then there is going to be a new URL that should be used for the accompanying files.

### PR DESCRIPTION
**Pull request by jhechtf**
Resolves #73

### CODE REVIEW

**Review by littledivy — APPROVED** [review]
LGTM

**Comment by littledivy** [comment]
@jhechtf Thanks. Is there anything left? can you mark the PR ready for review?

**Comment by jhechtf** [comment]
I was trying to think about how to test this to make sure it works but hadn't gotten a solution yet other than making another directory and making multiple runs to the cli.ts. If you're OK with that coming in a later PR then I can mark this as ready now.

**Comment by littledivy** [comment]
> If you're OK with that coming in a later PR then I can mark this as ready now.

Sure

**Comment by jhechtf** [comment]
Marked as ready then. won't be able to get to this for a few days as i have a vacation planned, but I'll get some more thorough testing of it up and ready.

**Pull request merged**
