### PR TITLE
add support for deno 1.25.0 buffer ffi type

### PR DESCRIPTION
**Pull request by tsar-boomba**
Uses buffer instead of pointer to align with deno 1.25.0

### CODE REVIEW

**Review by zifeo — APPROVED** [review]

**Comment by skanehira** [comment]
@tsar-boomba I think we should update version

https://github.com/denoland/deno_bindgen/blob/1cc5d34908331ed30fcc4ab803575e4d961b8e65/.github/workflows/ci.yml#L13-L15

**Review by littledivy — APPROVED** [review]
LGTM, thanks

**Review by littledivy — COMMENTED** [review]
Can you update the test generate code? Run `make test`

**Review by zifeo — APPROVED** [review]
@tsar-boomba Tested successfully, support is now complete 🎉 Can you maybe reformat with deno fmt? We should add this to the pipeline.

@littledivy Can you unblock the action for the pull request?

**Pull request merged**
